def try_me():
    print("Successful try!")
